//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.01.29 at 08:58:02 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://java-spring-projects/soap-web-services/courses", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package java_spring_projects.soap_web_services.courses;
